# seo
title: "gohu blog"
description: "anything"
url: "https://blog.gohu.dev"
author: "GOHU"

# path
baseurl: "/"
permalink: /:categories/:title
collections_dir: collections
collections:
  word:
    output: true
defaults:
  - scope:
      path: collections/_post
      type: post
    values:
      layout: post
  - scope:
      path: collections/_word/
      type: word
    values:
      permalink: /word/:title
      layout: post

# markdown
markdown: CommonMarkGhPages
commonmark:
  options: ["SMART", "FOOTNOTES"]
  extensions: ["strikethrough", "autolink", "table", "tagfilter"]
sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-avatar
  - jekyll-default-layout
  - jekyll-feed
  - jekyll-gist
  - jekyll-github-metadata
  - jekyll-include-cache
  - jekyll-mentions
  - jekyll-optional-front-matter
  - jekyll-redirect-from
  - jekyll-sass-converter
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-titles-from-headings
  - jemoji